<?php
/**
 * @file
 * Contains base function for module.
 */

/**
 * Implements hook_menu().
 */
function my_database_menu() {
  $items['my_database/insert'] = array(
    'title' => 'Page for insert data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('my_database_insert_form'),
    'access arguments' => array('administer site configuration'),
  );
  $items['my_database'] = array(
    'title' => 'Table with data',
    'page callback' => 'my_database_table_data_page',
    'access arguments' => array('administer site configuration'),
  );
  $items['my_database/%/delete'] = array(
    'title callback' => 'my_database_delete_page_title',
    'title arguments' => array(1),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('my_database_delete_form', 1),
    'access arguments' => array('administer site configuration'),
  );
  $items['my_database/%/update'] = array(
    'title callback' => 'my_database_update_page_title',
    'title arguments' => array(1),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('my_database_update_form', 1),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Build form for insert data.
 */
function my_database_insert_form($form, $form_state) {
  $form = array();
  $form['number'] = array(
    '#title' => t('Number'),
    '#type' => 'textfield',
    '#maxlegth' => 10,
    '#desciption' => t('Only numbers'),
    '#required' => TRUE,
  );
  $form['teaser'] = array(
    '#title' => t('Teaser'),
    '#type' => 'textfield',
    '#maxlegth' => 150,
    '#required' => TRUE,
  );
  $form['text'] = array(
    '#title' => t('Text'),
    '#type' => 'textarea',
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

/**
 * Validate for my_database_insert_form.
 */
function my_database_insert_form_validate($form, &$form_state) {
  if (drupal_strlen($form_state['values']['number']) > 10) {
    form_set_error('number', t('Field "@fieldname" must be less than @c chars.',
      array('@fieldname' => t('Number'), '@c' => 10)));
  }
  elseif (!ctype_digit($form_state['values']['number'])) {
    form_set_error('number', t('Field "number" must contains an integer.'));
  }
  if (drupal_strlen($form_state['values']['teaser']) > 150) {
    form_set_eror('teaser', t('Field "@fieldname" must be less than @c chars.',
      array('@filedname' => t('Teaser'), '@c' => 150)));
  }
}

/**
 * Submit for my_database_insert_form.
 */
function my_database_insert_form_submit($form, &$form_state) {
  $query = db_insert('custom_table')
    ->fields(array(
      'number' => $form_state['values']['number'],
      'teaser' => $form_state['values']['teaser'],
      'text'   => $form_state['values']['text'],
    ))
    ->execute();
  if ($query > 0) {
    drupal_set_message(t('Data has been successfully sent.'));
  }
  else {
    drupal_set_message(t("Data hasn't been sent"), 'error');
  }
}

/**
 * Build page with table.
 */
function my_database_table_data_page() {
  $header = array(t('ID'), t('Number'), t('Teaser'), t('Text'), t('Actions'));
  $rows = array();
  $query = db_select('custom_table', 't')
    ->fields('t', array('id', 'number', 'teaser', 'text'))
    ->execute();
  while ($value = $query->fetchAssoc()) {
    $rows[] = array(
      $value['id'],
      $value['number'],
      $value['teaser'],
      $value['text'],
      l(t('Update'), "my_database/{$value['id']}/update")
      . ' | '
      . l(t('Delete'), "my_database/{$value['id']}/delete"),
    );
  }
  return theme('table', array('header' => $header, 'rows' => $rows));
}

/**
 * Callback title for delete page.
 */
function my_database_delete_page_title($id) {
  $placeholders = array(':id' => $id);
  $number = db_query("SELECT `number` FROM {custom_table} WHERE `id` = :id", $placeholders)->fetchField();
  if ($number) {
    return t('Are you sure you want to delete item with number "@num"?', array('@num' => $number));
  }
  else {
    return t('Id not found.');
  }
}

/**
 * Build delete form page.
 */
function my_database_delete_form($form, $form_state) {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  $form['cancel'] = array(
    '#markup' => l(t('Cancel'), 'my_database'),
  );
  return $form;
}

/**
 * Submit function for delete form.
 */
function my_database_delete_form_submit($form, &$form_state) {
  $id = $form_state['build_info']['args'][0];
  $result = db_delete('custom_table')
    ->condition('id', $id)
    ->execute();
  $placeholders = array('@id' => $id);
  if ($result) {
    drupal_set_message(t('Record @id successfully removed.', $placeholders));
  }
  else {
    drupal_set_message(t('Record @id is undefined', $placeholders), 'warning');
  }
  $form_state['redirect'] = 'my_database';
}

/**
 * Callback title for delete page.
 */
function my_database_update_title($id) {
  $placeholders = array(':id' => $id);
  $namber = db_query("SELECT 'number' FROM {custom_table} WHERE 'id' = :id", $placeholders)->fetchField();
  if ($number) {
    return t('Edit item with number "@num"', array('@num' => $number));
  }
    else {
    return t('Id not found.');
  }
}

/**
 * Build form for update data.
 */
function my_database_update_form($form, $form_state) {
  $form = array();
  $id = $form_state['build_info']['args'][0];

  // Extract data.
  $data = db_select('custom_table', 'm')
    ->condition('m.id', $id)
    ->fields('m')
    ->execute()
    ->fetchAssoc();

  // Check id.
  if (empty($data) || empty($data['number'])) {
    $placeholders = array(
      '@id' => $id,
      '!back' => l(t('Go back'), 'my_database'),
    );
    $form['text'] = array(
      '#markup' => t('Undefined "@id" id. !back.', $placeholders),
    );
    return $form;
  }

  // Build form with default values.

  $form['number'] = array(
    '#title' => t('Number'),
    '#type' => 'textfield',
    '#maxlegth' => 10,
    '#desciption' => t('Only numbers'),
    '#required' => TRUE,
    '#default_value' => $data['number'],
  );
  $form['teaser'] = array(
    '#title' => t('Teaser'),
    '#type' => 'textfield',
    '#maxlegth' => 150,
    '#required' => TRUE,
    '#default_value' => $data['teaser'],
  );
  $form['text'] = array(
    '#title' => t('Text'),
    '#type' => 'textarea',
    '#required' => TRUE,
    '#default_value' => $data['text'],
  );

  // Action elements.
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  // Add existing validation.
  $form['#validate'][] = 'my_database_insert_form_validate';

  return $form;
}

/**
 * Submit function for update form.
 */
function my_database_update_form_submit($form, &$form_state) {
  $id = $form_state['build_info']['args'][0];
  $values = $form_state['values'];

  // Update data.
  $query = db_update('custom_table')
    ->fields(array(
      'number' => $values['number'],
      'teaser' => $values['teaser'],
      'text' => $values['text'],
    ))
    ->condition('id', $id)
    ->execute();

  // Check update status.
  if ($query) {
    drupal_set_message(t('Data updated successfully'));
  }
  else {
    drupal_set_message(t('Data is not updated'), 'warning');
  }

  $form_state['redirect'] = 'my_database';
}